"""users and shops

Revision ID: 0001
Revises: 
Create Date: 2026-09-25 22:43:54.467149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=False),
    sa.Column('address', sa.String(length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.Column('viber', sa.String(length=20), nullable=True),
    sa.Column('instagram', sa.String(length=60), nullable=True),
    sa.Column('terms_text', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('pickup_lead_days', sa.SmallInteger(), server_default=sa.text('2'), nullable=False),
    sa.Column('return_after_days', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('prep_days', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('cleaning_days', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('max_rental_days', sa.SmallInteger(), server_default=sa.text('7'), nullable=False),
    sa.Column('booking_mode', sa.String(length=16), server_default=sa.text("'request'"), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("booking_mode IN ('request', 'instant')", name=op.f('ck_shops_booking_mode')),
    sa.CheckConstraint("status IN ('draft', 'verified', 'published', 'suspended')", name=op.f('ck_shops_status')),
    sa.CheckConstraint('cleaning_days BETWEEN 0 AND 5', name=op.f('ck_shops_cleaning_days')),
    sa.CheckConstraint('max_rental_days BETWEEN 1 AND 14', name=op.f('ck_shops_max_rental_days')),
    sa.CheckConstraint('pickup_lead_days BETWEEN 0 AND 5', name=op.f('ck_shops_pickup_lead_days')),
    sa.CheckConstraint('prep_days BETWEEN 0 AND 2', name=op.f('ck_shops_prep_days')),
    sa.CheckConstraint('return_after_days BETWEEN 0 AND 3', name=op.f('ck_shops_return_after_days')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shops')),
    sa.UniqueConstraint('slug', name=op.f('uq_shops_slug'))
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('locale', sa.String(length=5), server_default=sa.text("'sq'"), nullable=False),
    sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('renter', 'shop', 'admin')", name=op.f('ck_users_kind')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone'))
    )
    op.create_table('shop_closures',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('shop_id', sa.BigInteger(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=200), server_default=sa.text("''"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_on >= starts_on', name=op.f('ck_shop_closures_range')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_shop_closures_shop_id_shops'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_closures'))
    )
    op.create_index(op.f('ix_shop_closures_shop_id'), 'shop_closures', ['shop_id'], unique=False)
    op.create_table('shop_customers',
    sa.Column('shop_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('first_booking_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('flagged', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_shop_customers_shop_id_shops')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_shop_customers_user_id_users')),
    sa.PrimaryKeyConstraint('shop_id', 'user_id', name=op.f('pk_shop_customers'))
    )
    op.create_table('shop_hours',
    sa.Column('shop_id', sa.BigInteger(), nullable=False),
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.Column('opens', sa.Time(), nullable=True),
    sa.Column('closes', sa.Time(), nullable=True),
    sa.Column('closed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6', name=op.f('ck_shop_hours_weekday')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_shop_hours_shop_id_shops'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shop_id', 'weekday', name=op.f('pk_shop_hours'))
    )
    op.create_table('shop_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('shop_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'staff')", name=op.f('ck_shop_users_role')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_shop_users_shop_id_shops')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_shop_users_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_users')),
    sa.UniqueConstraint('user_id', name=op.f('uq_shop_users_user_id'))
    )
    op.create_index(op.f('ix_shop_users_shop_id'), 'shop_users', ['shop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_users_shop_id'), table_name='shop_users')
    op.drop_table('shop_users')
    op.drop_table('shop_hours')
    op.drop_table('shop_customers')
    op.drop_index(op.f('ix_shop_closures_shop_id'), table_name='shop_closures')
    op.drop_table('shop_closures')
    op.drop_table('users')
    op.drop_table('shops')
    # ### end Alembic commands ###
