"""catalog

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-25 22:44:06.494422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('styles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('shop_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('occasion_tags', postgresql.ARRAY(sa.String(length=20)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('colour_family', sa.String(length=16), nullable=True),
    sa.Column('length', sa.String(length=8), nullable=True),
    sa.Column('stretch', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('adjustable_back', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price_cents >= 0', name=op.f('ck_styles_price')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_styles_shop_id_shops')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_styles')),
    sa.UniqueConstraint('shop_id', 'code', name=op.f('uq_styles_shop_id'))
    )
    op.create_index(op.f('ix_styles_shop_id'), 'styles', ['shop_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('shop_id', sa.BigInteger(), nullable=False),
    sa.Column('style_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('size', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'active'"), nullable=False),
    sa.Column('notes', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'cleaning', 'repair', 'retired', 'lost')", name=op.f('ck_items_status')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_items_shop_id_shops')),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], name=op.f('fk_items_style_id_styles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items')),
    sa.UniqueConstraint('id', 'style_id', 'shop_id', name='uq_items_id_style_shop'),
    sa.UniqueConstraint('shop_id', 'code', name=op.f('uq_items_shop_id'))
    )
    op.create_index('ix_items_style_size', 'items', ['style_id', 'size'], unique=False)
    op.create_table('style_images',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('style_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('storage_key', sa.String(length=200), nullable=False),
    sa.Column('width', sa.SmallInteger(), nullable=False),
    sa.Column('height', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], name=op.f('fk_style_images_style_id_styles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_style_images'))
    )
    op.create_index(op.f('ix_style_images_style_id'), 'style_images', ['style_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_style_images_style_id'), table_name='style_images')
    op.drop_table('style_images')
    op.drop_index('ix_items_style_size', table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_styles_shop_id'), table_name='styles')
    op.drop_table('styles')
    # ### end Alembic commands ###
