"""bookings

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-25 22:44:17.886994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ref', sa.String(length=8), nullable=False),
    sa.Column('shop_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('style_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('pickup_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('prep_days', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('cleaning_days', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('blocked_range', postgresql.DATERANGE(), sa.Computed("daterange(pickup_date - prep_days, return_date + cleaning_days, '[]')", persisted=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_channel', sa.String(length=20), nullable=True),
    sa.Column('fee_cents', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('price_cents', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('customer_note', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('staff_note', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('reason', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.column('item_id'), '='), (sa.column('blocked_range'), '&&'), where=sa.text("status IN ('hold', 'pending_shop', 'confirmed', 'picked_up')"), using='gist', name='ex_bookings_item_overlap'),
    sa.CheckConstraint("kind IN ('online', 'walk_in', 'phone', 'block')", name=op.f('ck_bookings_kind')),
    sa.CheckConstraint("status IN ('hold', 'pending_shop', 'confirmed', 'at_risk', 'picked_up', 'completed', 'cancelled_by_renter', 'cancelled_by_shop', 'expired', 'no_show', 'not_returned', 'declined')", name=op.f('ck_bookings_status')),
    sa.CheckConstraint('return_date >= pickup_date', name=op.f('ck_bookings_dates_order')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_bookings_created_by_users')),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_bookings_customer_id_users')),
    sa.ForeignKeyConstraint(['item_id', 'style_id', 'shop_id'], ['items.id', 'items.style_id', 'items.shop_id'], name='fk_bookings_item_style_shop'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_bookings_shop_id_shops')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings')),
    sa.UniqueConstraint('ref', name=op.f('uq_bookings_ref'))
    )
    op.create_index(op.f('ix_bookings_customer_id'), 'bookings', ['customer_id'], unique=False)
    op.create_index('ix_bookings_shop_pickup', 'bookings', ['shop_id', 'pickup_date'], unique=False)
    op.create_table('booking_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('from_status', sa.String(length=24), nullable=True),
    sa.Column('to_status', sa.String(length=24), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_kind', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("actor_kind IN ('renter', 'shop', 'admin', 'system')", name=op.f('ck_booking_events_actor_kind')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_booking_events_actor_id_users')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_booking_events_booking_id_bookings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_events'))
    )
    op.create_index(op.f('ix_booking_events_booking_id'), 'booking_events', ['booking_id'], unique=False)
    op.create_table('item_condition_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('booking_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('note', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('intake', 'returned_ok', 'returned_issue', 'status_change')", name=op.f('ck_item_condition_events_kind')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_item_condition_events_booking_id_bookings')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_item_condition_events_created_by_users')),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_item_condition_events_item_id_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_condition_events'))
    )
    op.create_index(op.f('ix_item_condition_events_item_id'), 'item_condition_events', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_condition_events_item_id'), table_name='item_condition_events')
    op.drop_table('item_condition_events')
    op.drop_index(op.f('ix_booking_events_booking_id'), table_name='booking_events')
    op.drop_table('booking_events')
    op.drop_index('ix_bookings_shop_pickup', table_name='bookings')
    op.drop_index(op.f('ix_bookings_customer_id'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
