"""provider onboarding

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-25 23:20:35.549568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_codes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("purpose IN ('signup', 'login')", name=op.f('ck_phone_codes_purpose')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phone_codes'))
    )
    op.create_index(op.f('ix_phone_codes_phone'), 'phone_codes', ['phone'], unique=False)
    op.add_column('shops', sa.Column('kind', sa.String(length=16), server_default=sa.text("'salon'"), nullable=False))
    op.add_column('shops', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('shops', sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('shops', sa.Column('terms_version', sa.String(length=20), nullable=True))
    op.add_column('shops', sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('styles', sa.Column('category', sa.String(length=16), nullable=True))
    op.add_column('styles', sa.Column('internal_ref', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_check_constraint(
        op.f("ck_shops_kind"), "shops", "kind IN ('salon', 'individual')"
    )
    op.create_check_constraint(
        op.f("ck_styles_category"),
        "styles",
        "category IN ('evening', 'bridal', 'engagement', 'mens_suit', 'traditional')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_styles_category"), "styles", type_="check")
    op.drop_constraint(op.f("ck_shops_kind"), "shops", type_="check")
    op.drop_column('users', 'phone_verified_at')
    op.drop_column('styles', 'internal_ref')
    op.drop_column('styles', 'category')
    op.drop_column('shops', 'onboarding_completed_at')
    op.drop_column('shops', 'terms_version')
    op.drop_column('shops', 'terms_accepted_at')
    op.drop_column('shops', 'verified_at')
    op.drop_column('shops', 'kind')
    op.drop_index(op.f('ix_phone_codes_phone'), table_name='phone_codes')
    op.drop_table('phone_codes')
    # ### end Alembic commands ###
